import type { Metadata } from "next";
import { Roboto, Cinzel } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar"
import Footer from "@/components/Footer"

// allows FontAwesome CSS (icons) to work in footer, imports the FontAwesome stylingsheet
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

// custom font via next/font
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-roboto'
});

const cinzel = Cinzel({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-cinzel'
});

export const metadata: Metadata = {
  title: "ELOVANCE Consulting",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${cinzel.variable} font-serif, ${roboto.variable} font-sans`}>
      <body className="bg-elo-base">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
